server:
    port: 8080
spring:
    application:
        name: onay
    datasource:
        password: Prazdnik21
        url: jdbc:postgresql://localhost:5432/onay_contacts
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
